"""Auto-generated Alembic script template."""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b85b06cc6fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
