const pages = document.querySelectorAll('.page');
const names = {dashboard:'Executive Dashboard',copilot:'AI Copilot Chat',risk:'Risk Radar','ci-failures':'CI Failure Intelligence',knowledge:'Knowledge Discovery',ingest:'Contribute Knowledge',incidents:'Incident Intelligence',sme:'SME Directory',security:'Security & Trust'};
function go(id){pages.forEach(p=>p.classList.toggle('show',p.id===id));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));document.querySelector('#page-name').textContent=names[id];document.querySelector('.sidebar').classList.remove('open');window.scrollTo(0,0)}
document.querySelectorAll('[data-page],[data-go]').forEach(e=>e.addEventListener('click',()=>go(e.dataset.page||e.dataset.go)));
document.querySelector('#menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
const input=document.querySelector('#question'), thread=document.querySelector('#thread');
const safeText=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function addMessage(kind, content){thread.insertAdjacentHTML('beforeend',`<div class="message ${kind==='user'?'user-msg':''}">${kind==='user'?'': '<b class="bot">✦</b>'}<div><p>${content}</p></div></div>`)}
async function answer(){const q=input.value.trim();if(!q)return;addMessage('user',safeText(q));input.value='';const pending=document.createElement('div');pending.className='message';pending.innerHTML='<b class="bot">✦</b><div><p>BuildPulse is coordinating CI, knowledge, risk, and SME agents…</p></div>';thread.appendChild(pending);thread.scrollIntoView({behavior:'smooth',block:'end'});try{const response=await fetch('/api/copilot/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});if(!response.ok)throw new Error(`API ${response.status}`);const result=await response.json();const sources=(result.sources||[]).map(source=>`<div class="source-card"><b>▤ ${safeText(source.title)}</b> ${source.url?`<a href="${safeText(source.url)}" target="_blank" rel="noopener">Open ${safeText(source.source||'source')} ↗</a>`:`Evidence used by the ${safeText(result.mode)} agent workflow.`}</div>`).join('');const trace=(result.agent_trace||[]).map(event=>safeText(event.agent)).join(' → ');const security=result.security?.redacted?`${result.security.findings_count} sensitive item(s) redacted before analysis · `:'Security scan passed · ';pending.innerHTML=`<b class="bot">✦</b><div><p>${safeText(result.answer).replace(/\n/g,'<br>')}</p>${sources}<small>${security}Audit ${safeText(result.audit_id||'not recorded')}</small><small>Agent trace: ${trace||'Copilot Response'}</small></div>`}catch(error){pending.innerHTML='<b class="bot">✦</b><div><p><strong>BuildPulse Copilot is temporarily unavailable.</strong> Please retry in a moment.</p><small>The request could not reach the grounded AI service; no fallback answer was generated.</small></div>'}thread.scrollIntoView({behavior:'smooth',block:'end'})}
document.querySelector('#send').addEventListener('click',answer);input.addEventListener('keydown',e=>{if(e.key==='Enter')answer()});document.querySelectorAll('.suggestions button').forEach(b=>b.addEventListener('click',()=>{input.value=b.textContent;answer()}));
const fileInput=document.querySelector('#fileInput'),fileReady=document.querySelector('#fileReady'),fileName=document.querySelector('#fileName');
fileInput.addEventListener('change',()=>{if(fileInput.files[0]){fileName.textContent=fileInput.files[0].name;fileReady.classList.add('show')}});
document.querySelector('#clearFile').addEventListener('click',()=>{fileInput.value='';fileReady.classList.remove('show')});
document.querySelector('#submitDoc').addEventListener('click',()=>{document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),4200)});

// Read-only Repository Intelligence. The static wireframe remains usable if
// FastAPI is unavailable, so the hackathon demo retains a graceful fallback.
const apiBase = '/api';
let repositoryServices = [];
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function apiGet(path){const response=await fetch(`${apiBase}${path}`);if(!response.ok)throw new Error(`API ${response.status}`);return response.json()}
function initials(name){return name.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase()}
function renderOwners(services){const table=document.querySelector('#owner-table');if(!table)return;const rows=services.map(service=>`<div><strong>${escapeHtml(service.name)}<small>${escapeHtml(service.team)}</small></strong><p><b class="avatar">${initials(service.primary_owner)}</b>${escapeHtml(service.primary_owner)}<small>Primary owner</small></p><p><b class="avatar green">${initials(service.backup_owner)}</b>${escapeHtml(service.backup_owner)}<small>Backup owner</small></p><span class="pill green">Covered</span></div>`).join('');table.innerHTML='<div class="tablehead"><span>SYSTEM</span><span>PRIMARY OWNER</span><span>BACKUP OWNER</span><span>STATUS</span></div>'+rows}
function renderPortfolio(overview){const card=document.querySelector('#portfolio-card');if(!card)return;card.innerHTML=`<div><small>LIVE REPOSITORY INTELLIGENCE</small><h3>${overview.service_count} services · ${overview.open_change_count} open changes</h3><p>Catalog ownership, dependencies, and branch diffs are being analyzed from the synthetic service repository.</p></div><div class="portfolio-metrics"><div><span>HIGH RISK</span><b>${overview.high_risk_change_count}</b></div><div><span>AWAITING APPROVAL</span><b>${overview.changes_awaiting_approval}</b></div></div>`}
function renderLiveCI(runs){const card=document.querySelector('#live-ci-card');if(!card||!runs.length)return;const run=runs[0];const passed=run.conclusion==='success';card.innerHTML=`<div><small>LIVE GITHUB ACTIONS · ${escapeHtml(run.source)}</small><h3>${escapeHtml(run.workflow)} · ${passed?'Passed':'Needs attention'}</h3><p>${escapeHtml(run.branch||'Unknown branch')} · ${escapeHtml(run.status)} · Latest workflow data collected from GitHub Actions.</p></div><div class="portfolio-metrics"><div><span>RESULT</span><b>${passed?'✓':'!'}</b></div><div><span>RUN ID</span><b>${escapeHtml(run.id)}</b></div></div>`}
function renderFailureIntelligence(analysis){const card=document.querySelector('#ci-failure-card');if(!card)return;const run=analysis.run||{};const source=run.source==='github'?'LIVE GITHUB FAILURE':'DEMO FAILURE FIXTURE';const confidence=analysis.confidence||{};card.innerHTML=`<div><small>${source} · ${escapeHtml(analysis.failure_class||'unknown')}</small><h3>${escapeHtml(run.job||run.workflow||'CI failure')}</h3><p>${escapeHtml(analysis.diagnosis)} <a data-go="copilot">Ask Copilot about the fix →</a></p></div><div class="portfolio-metrics"><div><span>CONFIDENCE</span><b>${escapeHtml(confidence.score||0)}%</b></div><div><span>RISK</span><b>${escapeHtml(analysis.risk?.risk_score||0)}</b></div></div>`;card.querySelectorAll('[data-go]').forEach(element=>element.addEventListener('click',()=>go(element.dataset.go)))}
function renderJiraDashboard(data){const readiness=data.release_readiness??0,incidents=data.open_incidents??0,blockers=data.release_blockers??0;document.querySelector('#jira-readiness').innerHTML=`${escapeHtml(readiness)}<span>%</span>`;document.querySelector('#jira-readiness-note').textContent=`Live from ${data.project_key} · ${blockers} high-priority blockers`;document.querySelector('#jira-readiness-bar').style.width=`${readiness}%`;document.querySelector('#jira-incident-count').textContent=incidents;document.querySelector('#jira-incident-note').innerHTML=`<b class="dot red"></b> ${incidents} open Jira incident${incidents===1?'':'s'}`;document.querySelector('#jira-release-card').innerHTML=`<div class="cardhead"><div><small>LIVE JIRA · ${escapeHtml(data.project_key)}</small><h3>Release readiness</h3></div><span class="pill ${blockers?'amber':'green'}">${blockers?'At risk':'Ready'}</span></div><div class="readiness"><div class="ring"><b>${escapeHtml(readiness)}%</b></div><div><b>${escapeHtml(blockers)} blocker${blockers===1?'':'s'} to resolve</b><p>Calculated from open High and Highest BuildPulse Jira issues.</p><a href="${escapeHtml((data.attention||[])[0]?.url||'#')}" target="_blank" rel="noopener">Open Jira project →</a></div></div>`;document.querySelector('#jira-attention').innerHTML=(data.attention||[]).slice(0,4).map(item=>`<li><b class="dot ${item.priority==='Highest'?'red':'amber'}"></b><div><strong>${escapeHtml(item.summary)}</strong><p>${escapeHtml(item.key)} · ${escapeHtml(item.service)} · ${escapeHtml(item.status)}</p></div><a class="pill ${item.priority==='Highest'?'red':'amber'}" href="${escapeHtml(item.url)}" target="_blank" rel="noopener">${escapeHtml(item.priority)}</a></li>`).join('')||'<li><div><strong>No open BuildPulse Jira issues</strong></div></li>';const counts=data.incidents_by_service||{},max=Math.max(1,...Object.values(counts));document.querySelector('#jira-service-chart').innerHTML=Object.entries({"loan-service":"Loan","payments-api":"Payments","api-gateway":"Gateway","identity-service":"Identity"}).map(([id,label])=>`<div style="height:${Math.max(8,((counts[id]||0)/max)*100)}%"><span>${label}</span></div>`).join('')}
async function loadJiraDashboard(){try{renderJiraDashboard(await apiGet('/jira/dashboard'))}catch(error){document.querySelector('#jira-readiness-note').textContent='Jira unavailable · fixture-free mode';document.querySelector('#jira-incident-note').innerHTML='<b class="dot amber"></b> Jira connection unavailable';document.querySelector('#jira-attention').innerHTML='<li><div><strong>Live Jira data unavailable</strong><p>Check Jira configuration and refresh.</p></div></li>'}}
let ciFailures=[];
function serviceLabel(serviceId){const service=repositoryServices.find(item=>item.id===serviceId);return service?.name||serviceId||'Unmapped service'}
function renderCiJobs(){const filter=document.querySelector('#ci-service-filter').value;const jobs=ciFailures.filter(job=>!filter||job.service_id===filter);document.querySelector('#ci-failure-count').textContent=jobs.length;document.querySelector('#ci-failure-source').textContent=jobs.some(job=>job.source==='github')?'Live GitHub Actions':'Demo fixture';const list=document.querySelector('#ci-job-list'),detail=document.querySelector('#ci-job-detail');detail.hidden=true;detail.innerHTML='<div class="ci-empty"><b>Select a failed job</b><p>Diagnosis, fixes, owners, risk, confidence, and evidence will appear here.</p></div>';if(!jobs.length){list.innerHTML='<div class="ci-empty"><b>No failed jobs found</b><p>Try another service or refresh GitHub Actions.</p></div>';return}list.innerHTML=jobs.map(job=>`<button class="ci-job" data-run-id="${escapeHtml(job.id)}"><span class="pill red">Failed</span><strong>${escapeHtml(job.job||job.workflow)}</strong><span>${escapeHtml(serviceLabel(job.service_id))}</span><span>${escapeHtml(job.branch||'Branch unavailable')}</span><small>${job.source==='github'?'LIVE GITHUB':'DEMO FIXTURE'} · ${escapeHtml(job.started_at||'Time unavailable')}</small><b aria-hidden="true">›</b></button>`).join('');list.querySelectorAll('.ci-job').forEach(button=>button.addEventListener('click',()=>selectCiJob(button)))}
async function selectCiJob(button){if(!button)return;document.querySelectorAll('.ci-job').forEach(item=>item.classList.toggle('selected',item===button));const detail=document.querySelector('#ci-job-detail');detail.hidden=false;detail.scrollIntoView({behavior:'smooth',block:'nearest'});detail.innerHTML='<div class="ci-empty">Analyzing failure evidence…</div>';try{const analysis=await apiGet(`/ci/failures/${encodeURIComponent(button.dataset.runId)}/analysis`);const run=analysis.run||{},confidence=analysis.confidence||{},risk=analysis.risk||{},owners=analysis.owners||{};const drivers=(confidence.drivers||[]).map(driver=>`<li><span>${escapeHtml(driver.signal)}</span><b>+${escapeHtml(driver.points)}</b></li>`).join('');const evidence=(analysis.evidence||[]).map(item=>`<details><summary>${escapeHtml(item.title)}</summary><pre>${escapeHtml(item.content||'No excerpt available')}</pre></details>`).join('');detail.innerHTML=`<div class="ci-detail-head"><div><span class="pill red">${escapeHtml(analysis.failure_class)} failure</span><h2>${escapeHtml(run.job||run.workflow)}</h2><p>${escapeHtml(serviceLabel(run.service_id))} · ${escapeHtml(run.failed_step||'Failed step unavailable')} · ${run.source==='github'?'Live GitHub':'Demo fixture'}</p></div><div class="ci-score"><b>${escapeHtml(confidence.score||0)}%</b><span>confidence</span></div></div><div class="ci-detail-grid"><section><small>DIAGNOSIS</small><p>${escapeHtml(analysis.diagnosis)}</p></section><section class="fix"><small>RECOMMENDED FIX</small><p>${escapeHtml(analysis.recommended_fix)}</p></section></div><div class="ci-facts"><div><small>CHANGE RISK</small><b>${escapeHtml(risk.risk_score||0)}/100 · ${escapeHtml(risk.risk_level||'unknown')}</b></div><div><small>PRIMARY OWNER</small><b>${escapeHtml(owners.primary||'Unassigned')}</b></div><div><small>BACKUP OWNER</small><b>${escapeHtml(owners.backup||'Unassigned')}</b></div><div><small>LOG SECURITY</small><b>${analysis.security?.redacted?'Sensitive data redacted':analysis.security?.available?'Scan passed':'Metadata only'}</b></div></div><div class="ci-analysis-lower"><section><h3>Confidence drivers</h3><ul>${drivers}</ul></section><section><h3>Recommended checks</h3><ul>${(risk.recommended_checks||[]).map(check=>`<li>${escapeHtml(check)}</li>`).join('')}</ul></section></div><div class="ci-evidence"><h3>Evidence</h3>${evidence}</div><div class="ci-detail-actions"><button class="primary" id="ci-ask-copilot">✦ Ask Copilot</button>${run.url?`<a class="outline" href="${escapeHtml(run.url)}" target="_blank" rel="noopener">Open GitHub job ↗</a>`:''}<small>Audit ${escapeHtml(analysis.audit_id)}</small></div>`;document.querySelector('#ci-ask-copilot').addEventListener('click',()=>{input.value=`Explain the ${serviceLabel(run.service_id)} CI failure and recommended fix`;go('copilot');answer()})}catch(error){detail.innerHTML='<div class="ci-empty"><b>Analysis unavailable</b><p>The backend could not analyze this failed job.</p></div>'}}
async function loadCiFailures(){const list=document.querySelector('#ci-job-list');list.innerHTML='<div class="ci-empty">Loading failed jobs…</div>';try{const response=await apiGet('/ci/failures');ciFailures=response.items||[];renderCiJobs()}catch(error){list.innerHTML='<div class="ci-empty"><b>Failed jobs unavailable</b><p>Check the API connection and try again.</p></div>'}}
async function renderServiceContext(serviceId){if(!serviceId)return;try{const service=await apiGet(`/services/${encodeURIComponent(serviceId)}`);const card=document.querySelector('#portfolio-card');if(card)card.innerHTML=`<div><small>SELECTED SERVICE · LIVE CATALOG</small><h3>${escapeHtml(service.name)}</h3><p>Primary: ${escapeHtml(service.primary_owner)} · Backup: ${escapeHtml(service.backup_owner)} · Dependencies: ${escapeHtml(service.depends_on.join(', ')||'None')}</p></div><div class="portfolio-metrics"><div><span>TIER</span><b>${escapeHtml(service.tier)}</b></div><div><span>DEPENDED ON BY</span><b>${service.depended_on_by.length}</b></div></div>`}catch(error){console.info('Service context fallback active',error)}}
function renderRisk(risk){document.querySelector('#pr-risk-detail').hidden=false;document.querySelector('#risk-score').textContent=risk.risk_score;const level=document.querySelector('#risk-level');level.textContent=`${risk.risk_level} risk`;level.className=`pill ${risk.risk_level==='high'?'red':risk.risk_level==='medium'?'amber':'green'}`;document.querySelector('#risk-title').textContent=`PR #${risk.pr_number} · ${risk.service}`;const historical=risk.historical_incidents||[],top=historical[0];document.querySelector('#risk-summary').textContent=`${risk.changed_files.length} changed files · Primary owner: ${risk.owners.primary} · Review status: ${risk.owners.review_status}.${top?` Similar resolved incident: ${top.key} (${top.similarity_score}%).`:''}`;const open=document.querySelector('#risk-open-pr');open.href=risk.url||`https://github.com/vickypandeyindia462-code/buildpulse-demo-services/pull/${risk.pr_number}`;document.querySelector('#risk-formula').innerHTML='<small>DETERMINISTIC SCORE</small>'+risk.drivers.slice(-3).map(driver=>`<p>${escapeHtml(driver.factor)} <b>${driver.points>0?'+':''}${driver.points}</b></p>`).join('');document.querySelector('#risk-drivers').innerHTML=risk.drivers.map((driver,index)=>{const incident=historical.find(item=>item.key===driver.jira_issue);return `<article class="card"><span class="pill ${driver.jira_issue?'red':index===1?'amber':'blue'}">${driver.points>0?'+':''}${driver.points} points</span><h3>${escapeHtml(driver.factor)}</h3><p>${incident?`${escapeHtml(incident.key)} · ${escapeHtml(incident.similarity_score)}% similar · resolved by ${escapeHtml(incident.resolved_by)}`:driver.dependencies?`Affected dependencies: ${escapeHtml(driver.dependencies.join(', '))}.`:`PR #${risk.pr_number} · ${escapeHtml(risk.service)}`}</p>${incident?`<a href="${escapeHtml(incident.url)}" target="_blank" rel="noopener">Review historical resolution →</a>`:`<a>${escapeHtml(risk.recommended_checks[index]||risk.recommended_checks[0])}</a>`}</article>`}).join('')}
let pullRequests=[];
function prService(pr){const branch=(pr.branch||'').toLowerCase();return branch.includes('payment')?'payments-api':branch.includes('gateway')?'api-gateway':branch.includes('identity')?'identity-service':branch.includes('loan')?'loan-service':''}
function renderPrRows(){const filter=document.querySelector('#risk-service-filter').value,items=pullRequests.filter(pr=>!filter||prService(pr)===filter),list=document.querySelector('#pr-list');document.querySelector('#pr-risk-detail').hidden=true;if(!items.length){list.innerHTML='<div class="ci-empty"><b>No open pull requests found</b></div>';return}list.innerHTML=items.map(pr=>`<button class="ci-job pr-job" data-pr="${pr.number}"><span class="pill blue">Open</span><strong>#${pr.number} · ${escapeHtml(pr.title)}</strong><span>${escapeHtml(serviceLabel(prService(pr)))}</span><span>${escapeHtml(pr.branch)} → ${escapeHtml(pr.base)}</span><small>LIVE GITHUB · ${escapeHtml(pr.updated_at)}</small><b aria-hidden="true">›</b></button>`).join('');list.querySelectorAll('.pr-job').forEach(button=>button.addEventListener('click',async()=>{list.querySelectorAll('.pr-job').forEach(row=>row.classList.toggle('selected',row===button));document.querySelector('#pr-risk-detail').hidden=false;document.querySelector('#risk-title').textContent='Analyzing pull request…';try{renderRisk(await apiGet(`/pull-requests/${button.dataset.pr}/risk`));document.querySelector('#pr-risk-detail').scrollIntoView({behavior:'smooth',block:'nearest'})}catch(error){document.querySelector('#risk-title').textContent='Risk analysis unavailable'}}))}
async function loadPullRequests(){const list=document.querySelector('#pr-list');list.innerHTML='<div class="ci-empty">Loading open GitHub pull requests…</div>';try{const response=await apiGet('/pull-requests');pullRequests=response.items||[];renderPrRows()}catch(error){list.innerHTML='<div class="ci-empty"><b>Pull requests unavailable</b><p>Check GitHub access and refresh.</p></div>'}}
async function loadKnowledge(){const container=document.querySelector('#knowledge-results'),query=document.querySelector('#knowledge-query').value.trim(),source=document.querySelector('input[name="knowledge-source"]:checked').value;container.innerHTML='<p class="result-count">Searching approved knowledge sources…</p>';try{const response=await apiGet(`/knowledge/search?q=${encodeURIComponent(query)}&source=${encodeURIComponent(source)}`);container.innerHTML=`<p class="result-count">${response.total} results · ${escapeHtml((response.sources||[]).join(' + ')||source)} · sorted by relevance</p>`+(response.items||[]).map(item=>`<article class="result"><span class="docicon ${item.source==='confluence'?'purplebg':''}">${item.source==='confluence'?'◇':'▤'}</span><div><div><span class="pill ${item.source==='confluence'?'blue':'amber'}">${escapeHtml(item.source)}</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.snippet||item.content||'')}</p><small><b>${escapeHtml(item.score||0)}% match</b></small></div>${item.url?`<a class="outline" href="${escapeHtml(item.url)}" target="_blank" rel="noopener" aria-label="Open ${escapeHtml(item.title)}">↗</a>`:'<span class="pill">LOCAL</span>'}</article>`).join('')||'<div class="ci-empty"><b>No matching knowledge found</b></div>'}catch(error){container.innerHTML='<div class="ci-empty"><b>Knowledge search unavailable</b><p>Check the API and Confluence connection.</p></div>'}}
async function loadRepositoryIntelligence(){try{const overview=await apiGet('/portfolio/overview');repositoryServices=overview.services;renderPortfolio(overview);renderOwners(repositoryServices);const selector=document.querySelector('#dashboard-service-select');repositoryServices.forEach(service=>selector.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(service.id)}">${escapeHtml(service.name)}</option>`));selector.addEventListener('change',()=>renderServiceContext(selector.value));const riskFilter=document.querySelector('#risk-service-filter');repositoryServices.forEach(service=>riskFilter.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(service.id)}">${escapeHtml(service.name)}</option>`));document.querySelector('#sme-search').addEventListener('input',event=>{const query=event.target.value.toLowerCase();renderOwners(repositoryServices.filter(service=>[service.name,service.team,service.primary_owner,service.backup_owner].join(' ').toLowerCase().includes(query)))});try{renderLiveCI((await apiGet('/ci/runs')).items||[])}catch(error){console.info('Live CI card unavailable',error)}try{const failures=(await apiGet('/ci/failures')).items||[];if(failures.length)renderFailureIntelligence(await apiGet(`/ci/failures/${encodeURIComponent(failures[0].id)}/analysis`))}catch(error){console.info('CI failure intelligence unavailable',error)}}catch(error){console.info('Repository Intelligence fallback active',error)}}
async function loadCiServiceFilter(){try{const response=await apiGet('/services');const selector=document.querySelector('#ci-service-filter');(response.items||[]).forEach(service=>selector.insertAdjacentHTML('beforeend',`<option value="${escapeHtml(service.id)}">${escapeHtml(service.name)}</option>`))}catch(error){console.info('CI service filter unavailable',error)}}
loadRepositoryIntelligence();
loadJiraDashboard();
loadPullRequests();
loadKnowledge();
loadCiServiceFilter();
document.querySelector('#ci-service-filter').addEventListener('change',renderCiJobs);
document.querySelector('#refresh-ci-failures').addEventListener('click',loadCiFailures);
document.querySelector('#risk-service-filter').addEventListener('change',renderPrRows);
document.querySelector('#refresh-prs').addEventListener('click',loadPullRequests);
document.querySelector('#knowledge-search').addEventListener('click',loadKnowledge);
document.querySelector('#knowledge-query').addEventListener('keydown',event=>{if(event.key==='Enter')loadKnowledge()});
document.querySelectorAll('input[name="knowledge-source"]').forEach(input=>input.addEventListener('change',loadKnowledge));
loadCiFailures();
